### ISSUE TITLE
Integrate shunit2 for testing

### ISSUE THREAD

**Issue by jeffhung** [jeffhung/python.make#6]
Got the idea to fix issue #5 , but I would like to have more complete testing/evaluation for different scenarios. Therefore, we could integrate [shunit2](https://www.google.com/search?q=shunit2) to build the framework to validate the scenarios.

* [x] Select the canonical shunit2 version (there are many variant versions in the wild)
* [x] Integrate into build process
* [x] Implement some test cases to validate the integration

**Comment by jeffhung** [comment]
The shunit2 version recognized by popular package systems:

| System       | Canonical `shunit2` version      | Known Through                                                                                     |
|--------------|----------------------------------|---------------------------------------------------------------------------------------------------|
| Homebrew     | https://github.com/kward/shunit2 | `brew info shunit2`                                                                               |
| NetBSD 8.1   | https://github.com/kward/shunit2 | [link](https://netbsd.pkgs.org/8.1/netbsd-amd64/shunit2-2.1.6.tgz.html)                           |
| CentOS 6     | http://code.google.com/p/shunit2 | [link](https://centos.pkgs.org/6/epel-x86_64/shunit2-2.1.6-3.el6.noarch.rpm.html)                 |
| Fedora 30    | http://code.google.com/p/shunit2 | [link](https://fedora.pkgs.org/30/fedora-x86_64/shunit2-2.1.6-16.fc30.noarch.rpm.html)            |
| Debian 10    | http://code.google.com/p/shunit2 | [link](https://debian.pkgs.org/10/debian-main-amd64/shunit2_2.1.6-1.1_all.deb.html)               |
| Ubuntu 19.10 | http://code.google.com/p/shunit2 | [link](https://ubuntu.pkgs.org/19.10/ubuntu-universe-amd64/shunit2_2.1.6-1.1ubuntu1_all.deb.html) |

The [kward/shunit2](https://github.com/kward/shunit2) version is very different from the [google code version](http://code.google.com/p/shunit2), according to the folder structure.

We shall also consider whether or not the JUnit XML patch could be applied. See: https://code.google.com/archive/p/shunit2/issues/16

**Comment by jeffhung** [comment]
Noticed the [announcement](https://code.google.com/archive/p/shunit2/) on google code:
> NOTICE(2015-06-26): shunit2 has moved to GitHub! http://github.com/kward/shunit2

As the google code version is the previous canonical one, based on the announcement, we shall select the [kward/shunit2](https://github.com/kward/shunit2) version.

**Comment by sio** [comment]
Have you considered using Python for unit testing?

Since this project already implies being familiar with Python that won't be a new dependency, and unit testing frameworks in Python are very advanced.

I understand that going that way will imply a lot of `subprocess` calls, but those may be abstracted away with a few helper functions for the most common use cases. Shell scripts for unit tests will be rather tricky to get right in regards of whitespace quoting, regex matching, etc - so Python seems like a worthwhile alternative.

**Comment by jeffhung** [comment]
As the major use case of `python.make` is to provision the python environment, I choose to test with `shunit2` in order to have no python in prerequisites.

**Comment by sio** [comment]
Ok, that works too :)

To support my suggestion I was going to add an example of Python-based tests for Makefile before you replied. Now it's too late but [here it is anyways](https://github.com/sio/Makefile.venv/blob/7db4da97a6fd5b10045462a72b5efa53a17097b9/tests/test_venv.py) (I wrote it for another Makefile project, but the code is easily reusable).
